-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 22:55:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Event_Planning
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Event_Planning` ;

-- -----------------------------------------------------
-- Schema Event_Planning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Event_Planning` DEFAULT CHARACTER SET utf8 ;
USE `Event_Planning` ;

-- -----------------------------------------------------
-- Table `Event_Planning`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Address` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Address` (
  `Address_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `City` CHAR(12) NOT NULL,
  `Street` CHAR(12) NOT NULL,
  `Phone_no` VARCHAR(45) NOT NULL,
  `Mobile_no` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Address_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Booked_By`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Booked_By` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Booked_By` (
  `Booker_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Contact_no` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Event_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Booker_ID`),
  INDEX `fk_Booked_By_Events1_idx` (`Event_ID` ASC) ,
  CONSTRAINT `fk_Booked_By_Events1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `Event_Planning`.`Events` (`Event_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Booking_Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Booking_Status` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Booking_Status` (
  `Booking_Status_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL COMMENT 'Confirmed or Provisonal',
  PRIMARY KEY (`Booking_Status_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Contacts` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Contacts` (
  `Contacts_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Contact_Name` CHAR(12) NOT NULL,
  `Telephone_no` VARCHAR(45) NOT NULL,
  `Website` VARCHAR(45) NULL DEFAULT NULL,
  `Organizers_ID` INT UNSIGNED NOT NULL,
  `Address_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Contacts_ID`),
  INDEX `fk_Contacts_Organizers1_idx` (`Organizers_ID` ASC) ,
  INDEX `fk_Contacts_Address1_idx` (`Address_ID` ASC) ,
  CONSTRAINT `fk_Contacts_Organizers1`
    FOREIGN KEY (`Organizers_ID`)
    REFERENCES `Event_Planning`.`Organizers` (`Organizers_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contacts_Address1`
    FOREIGN KEY (`Address_ID`)
    REFERENCES `Event_Planning`.`Address` (`Address_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Database_Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Database_Admin` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Database_Admin` (
  `DBadmin_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DBadmin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Event_Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Event_Status` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Event_Status` (
  `Event_Status_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL COMMENT 'e.g Registered, Cancelled,Paid,Booked ETC',
  PRIMARY KEY (`Event_Status_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Event_Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Event_Types` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Event_Types` (
  `Event_Types_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL COMMENT 'Concert,Dinner,Prade, Marriage etc',
  PRIMARY KEY (`Event_Types_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Events` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Events` (
  `Event_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Event_Name` VARCHAR(45) NOT NULL,
  `Start_date` VARCHAR(45) NOT NULL,
  `End_date` VARCHAR(45) NOT NULL,
  `Number_of_partcipants` INT NOT NULL,
  `Discount` INT NOT NULL,
  `Amount_Paid` INT NOT NULL,
  `Calculated_Cost` INT NOT NULL,
  `Extra_Cost` INT NOT NULL,
  `Comments` VARCHAR(45) NULL DEFAULT NULL,
  `Other_Details` VARCHAR(45) NULL DEFAULT NULL,
  `Organizers_ID` INT UNSIGNED NOT NULL,
  `Event_Status_ID` INT UNSIGNED NOT NULL,
  `Free_or_Commercial_ID` INT UNSIGNED NOT NULL,
  `Event_Types_ID` INT UNSIGNED NOT NULL,
  `Venue_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Event_ID`),
  INDEX `fk_Events_Organizers1_idx` (`Organizers_ID` ASC) ,
  INDEX `fk_Events_Event_Status1_idx` (`Event_Status_ID` ASC) ,
  INDEX `fk_Events_Free_or_Commercial1_idx` (`Free_or_Commercial_ID` ASC) ,
  INDEX `fk_Events_Event_Types1_idx` (`Event_Types_ID` ASC) ,
  INDEX `fk_Events_Venue1_idx` (`Venue_ID` ASC) ,
  CONSTRAINT `fk_Events_Organizers1`
    FOREIGN KEY (`Organizers_ID`)
    REFERENCES `Event_Planning`.`Organizers` (`Organizers_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Events_Event_Status1`
    FOREIGN KEY (`Event_Status_ID`)
    REFERENCES `Event_Planning`.`Event_Status` (`Event_Status_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Events_Free_or_Commercial1`
    FOREIGN KEY (`Free_or_Commercial_ID`)
    REFERENCES `Event_Planning`.`Free_or_Commercial` (`Free_or_Commercial_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Events_Event_Types1`
    FOREIGN KEY (`Event_Types_ID`)
    REFERENCES `Event_Planning`.`Event_Types` (`Event_Types_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Events_Venue1`
    FOREIGN KEY (`Venue_ID`)
    REFERENCES `Event_Planning`.`Venue` (`Venue_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Free_or_Commercial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Free_or_Commercial` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Free_or_Commercial` (
  `Free_or_Commercial_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL COMMENT 'Commercial,Free,Partially Free',
  PRIMARY KEY (`Free_or_Commercial_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Organizers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Organizers` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Organizers` (
  `Organizers_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` CHAR(12) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Organizers_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Rooms` (
  `Room_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Room_Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Rate_per_day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Room_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Services` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Services` (
  `Service_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Service_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Space_Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Space_Request` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Space_Request` (
  `Space_Request_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Occupancy_Y_N` VARCHAR(45) NOT NULL,
  `From_date` VARCHAR(45) NOT NULL,
  `To_Date` VARCHAR(45) NULL,
  `Room_ID` INT UNSIGNED NOT NULL,
  `Booking_Status_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Space_Request_ID`),
  INDEX `fk_Space_Request_Rooms1_idx` (`Room_ID` ASC) ,
  INDEX `fk_Space_Request_Booking_Status1_idx` (`Booking_Status_ID` ASC) ,
  CONSTRAINT `fk_Space_Request_Rooms1`
    FOREIGN KEY (`Room_ID`)
    REFERENCES `Event_Planning`.`Rooms` (`Room_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Space_Request_Booking_Status1`
    FOREIGN KEY (`Booking_Status_ID`)
    REFERENCES `Event_Planning`.`Booking_Status` (`Booking_Status_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Sponsors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Sponsors` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Sponsors` (
  `Sponsors_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Contact_no` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Event_ID` INT UNSIGNED NOT NULL,
  `Service_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Sponsors_ID`),
  INDEX `fk_Sponsors_Events1_idx` (`Event_ID` ASC) ,
  INDEX `fk_Sponsors_Services1_idx` (`Service_ID` ASC) ,
  CONSTRAINT `fk_Sponsors_Events1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `Event_Planning`.`Events` (`Event_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sponsors_Services1`
    FOREIGN KEY (`Service_ID`)
    REFERENCES `Event_Planning`.`Services` (`Service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event_Planning`.`Venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event_Planning`.`Venue` ;

CREATE TABLE IF NOT EXISTS `Event_Planning`.`Venue` (
  `Venue_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Venue_Name` VARCHAR(45) NOT NULL,
  `Other_Details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Venue_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
